/*
 * This source file was generated by the Gradle 'init' task
 */
package org.assignment;

public class ListSynchronization {

    public boolean simpleTestMethod() {
        return true;
    }

    public boolean add(int delayMillis) {
        try {
            Thread.sleep(delayMillis);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            return false;
        }

        return true;
    }

    public boolean update(int delayMillis) {
        return add(delayMillis);
    }

    public boolean delete(int delayMillis) {
        return add(delayMillis);
    }
}