/*
 * This source file was generated by the Gradle 'init' task
 */
package org.assignment;

public class ListSynchronization {

    public boolean simpleTestMethod() {
        return true;
    }

    public boolean delayedMethod(int delayMillis) {
        try {
            Thread.sleep(delayMillis);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            return false;
        }

        return true;
    }
}